### ISSUE TITLE
关于wilderworld模组中冰块(ice_cube)无限刷取的问题

### ISSUE THREAD

**Issue by Tonoseihon** [QF-project/QFserver-Wonder#11]
### 检查项

- [X] **这个Bug是可复现的** 即其他玩家也可以同样触发这个Bug (可选)
- [X] **Bug的确是非游戏预期内容** 请在[MC模组百科](https://mcmod.cn/)中确认这个模组的功能
- [X] 我已在 [Issues 页面](https://github.com/Qian-F/QFserver-Wonder/issues) 中搜索，确认了这一Bug未被提交过。

### 描述

wilderworld里的ice_cube的获得方式如下:
手拿冰(minecraft:ice)右键装满水的炼药锅
此时炼药锅会显示如下图
<img width="526" alt="image" src="https://github.com/Qian-F/QFserver-Wonder/assets/99337738/40d3880f-8810-4a1d-b393-318cb271257f">
可以通过不断右键来获得冰块(ice_cube)
同时炼药锅内的冰会减少，如下
<img width="694" alt="image" src="https://github.com/Qian-F/QFserver-Wonder/assets/99337738/8c0e039a-d99a-4faa-b716-e94564046ce0">
同时当我们手中持有冰块(ice_cube)时，右键其会使其中的冰增加
但是
当前游戏中，倘若我们向其中补充冰块(ice_cube)
我们手中的冰块(ice_cube)根本就不会消耗，即实现了无损耗的补充
这导致了冰块(ice_cube)可以无限地通过此方式生成
而不是通过预期中的向装满水的炼药锅中加入一块冰(minecraft:ice)来获得定量的冰块(ice_cube)

**Comment by Qian-F** [comment]
尝试单模组启动是否会出现类似问题

**Comment by Qian-F** [comment]
确定是模组自身问题，稍后会发issue

**Comment by Qian-F** [comment]
issue已交：https://github.com/0xKY/WilderWorld/issues/10

**Comment by Qian-F** [comment]
疑似作者不再维护此模组，请求玩家社区帮助

**Comment by Qian-F** [comment]
作者已回复，将在下版本修复
https://github.com/0xKY/WilderWorld/issues/10#issuecomment-1595008348

**Comment by Qian-F** [comment]
作者已不维护1.18.2版本
此模组将在下版本删除
