### ISSUE TITLE
在挖掘饮酒作乐模组的发酵桶后游戏异常退出

### ISSUE THREAD

**Issue by MonianHello** [QF-project/QFserver-Wonder#13]
### 检查项

- [X] **我没有自行添加其他模组** 安装其他Mod后的客户端崩溃不是整合包自身的原因，若有需要请前往 [新功能提案](https://github.com/Qian-F/QFserver-Wonder/issues/new?assignees=&labels=%C2%B7+%E6%96%B0%E5%8A%9F%E8%83%BD%2C%E5%8F%8D%E9%A6%88&template=feature.yml) 
- [X] **目前我的客户端是最新的** 务必在更新客户端后进入服务器
- [X] 我已在 [Issues 页面](https://github.com/Qian-F/QFserver-Wonder/issues) 中搜索，确认了这一问题未被提交过。

### 描述

在挖掘 [饮酒作乐 (Brewin' And Chewin')](https://www.mcmod.cn/item/607330.html)_(brewinandchewin-fabric-2.0.0+1.18.2.jar)_ 模组的[发酵桶 (Keg)](https://www.mcmod.cn/item/607330.html)后游戏异常退出

(这个发酵桶放置在一个多方块结构之上):
![image](https://github.com/Qian-F/QFserver-Wonder/assets/50223265/c3078cf8-df76-4d32-a79f-47ec3fd94b79)

### 错误报告、日志与附件

[错误报告-2023-6-4_20.16.57.zip](https://github.com/Qian-F/QFserver-Wonder/files/11645599/-2023-6-4_20.16.57.zip)

**Comment by Qian-F** [comment]
还是有一些问题需要明确：
1. 更新后新制作的酒桶是否会导致崩溃？
2. 所谓多方块结构仅此一种会导致崩溃还是还有其他多方块结构也会导致崩溃？
3. 是否为单模组问题？

**Comment by MonianHello** [comment]
> 还是有一些问题需要明确：
> 
> 1. 更新后新制作的酒桶是否会导致崩溃？
> 2. 所谓多方块结构仅此一种会导致崩溃还是还有其他多方块结构也会导致崩溃？
> 3. 是否为单模组问题？

1.会
2.见视频复现：

https://github.com/QF-project/QFserver-Wonder/assets/50223265/1c926112-c3a1-4404-be8a-c4544b770be1


3.尚不明确

**Comment by Qian-F** [comment]
修复版已发布
https://www.curseforge.com/minecraft/mc-mods/brewin-and-chewin-fabric/files/4585056
