### ISSUE TITLE
关于铜管模组无法正常输出物品的bug

### ISSUE THREAD

**Issue by Tonoseihon** [QF-project/QFserver-Wonder#14]
### 检查项

- [X] **此Bug出现在服务器中** 在单人游戏内的错误/崩溃将不予处理
- [X] **Bug的确是非游戏预期内容** 请在[MC百科](https://mcmod.cn/)/[Curseforge](https://www.curseforge.com/minecraft)/[Modrinth](https://modrinth.com/)中确认这个模组的功能
- [X] 我已在 [ISSUE页面](https://github.com/QF-project/QFserver-Wonder/issues) 中搜索, 确认了这一Bug未被提交过
- [X] **这个Bug是可复现的** 即其他玩家也可以同样触发这个Bug (可选)

### 描述

此bug的影响是恶劣的，因为它直接让铜管失去了意义
当前测试服中，铜管在接出容器时，只会检测该容器的第一格和第二格的物品，且只输出第一格的物品
具象化的表现为，箱子只有第一格的物品会被输出，而当第二格有物品时，铜管只会发出运输物品的声音而不会输出
其余情况下即第三格及以后的格子有物品也不会产生任何影响，即既不会输出物品也不会发出声音

**Comment by Tonoseihon** [comment]
附加，当铜管加长时，物品会因不知名的原因停留在最开始也就是第一个管道里

**Comment by Tonoseihon** [comment]
再附加（，当铜管中出现第二种物品时会才能正常运输到下一个，且仅运输第一种

**Comment by Qian-F** [comment]
未确认：
1. 单模组是否出现bug

**Comment by Qian-F** [comment]
https://github.com/AViewFromTheTop/SimpleCopperPipesMC/issues/17
issue 已交

**Comment by Qian-F** [comment]
将删除，如作者修复则加回
