### ISSUE TITLE
无法购买endrem:evil_eye物品

### ISSUE THREAD

**Issue by MonianHello** [QF-project/QFserver-Wonder#15]
### 检查项

- [X] **此Bug出现在服务器中** 在单人游戏内的错误/崩溃将不予处理
- [X] **Bug的确是非游戏预期内容** 请在[MC百科](https://mcmod.cn/)/[Curseforge](https://www.curseforge.com/minecraft)/[Modrinth](https://modrinth.com/)中确认这个模组的功能
- [X] 我已在 [ISSUE页面](https://github.com/QF-project/QFserver-Wonder/issues) 中搜索, 确认了这一Bug未被提交过
- [X] **这个Bug是可复现的** 即其他玩家也可以同样触发这个Bug (可选)

### 描述

endrem:evil_eye物品与大师级牧师村民无法交换，之前从未购买过。现实第二天也不可以
![image](https://github.com/QF-project/QFserver-Wonder/assets/50223265/754e3059-a687-468a-94a2-44c9300e9f3a)

### 重现步骤

https://github.com/QF-project/QFserver-Wonder/assets/50223265/9e163eb1-bb40-49e7-a8c2-29e0e0873ccc

**Comment by Qian-F** [comment]
需等待一段时间后就可以换了
