### ISSUE TITLE
升级机械动力模组至最新的0.5.1b

### ISSUE THREAD

**Issue by Tonoseihon** [QF-project/QFserver-Wonder#21]
### 检查项

- [X] **此建议不涉及模组的增删** 针对需要增删模组的建议，请前往 [新功能提案](https://github.com/Qian-F/QFserver-Wonder/issues/new?assignees=&labels=%C2%B7+%E6%96%B0%E5%8A%9F%E8%83%BD%2C%E5%8F%8D%E9%A6%88&template=feature.yml)
- [X] 我已在 [Issues 页面](https://github.com/Qian-F/QFserver-Wonder/issues) 中搜索，确认了这一建议未被提交过。

### 内容

当前游戏中近乎所有的机械动力附属都已经适配了0.5.1的更新
所以是时候更新机械动力了：）

**Comment by Qian-F** [comment]
一些0.5.0的附属暂未适配0.5.1版本 适配后将会更新

**Comment by Tonoseihon** [comment]
本服内所有机械动力附属更新情况如下：
create chunkloading：已更新 
https://www.curseforge.com/minecraft/mc-mods/create-chunkloading/files/4571166
create crafts&additions：已更新
https://modrinth.com/mod/createaddition/version/fabric-1.18.2-20230508b
Create: Crystal Clear：已更新
https://modrinth.com/mod/create-crystal-clear-fabric/version/1.0-fabric-patch1
Create: Steam n’ Rails：已更新
https://modrinth.com/mod/create-steam-n-rails/version/1.2.6-fabric
KubeJS Create：有必要吗（
CreatePlus：已更新
https://modrinth.com/mod/createplus/version/1.0-beta4
Create Enchant Additions：屁用没有，功能重复，建议删除（这就提issue
CC:C Bridge：0.5.1后create已支持lua，意味CC可以直接接入create而不需要该联动，更新后可删除（

综上，快更吧（（（（（（

**Comment by Qian-F** [comment]
好好好 更更更（明天或者后天

**Comment by Qian-F** [comment]
想起来了 是这个附属
https://github.com/DM-Fabric-Ports/Create-Crystal-Clear/issues/6
我其实一直在关注机械动力的更新（（

**Comment by Qian-F** [comment]
> 想起来了 是这个附属 [DM-Fabric-Ports/Create-Crystal-Clear#6](https://github.com/DM-Fabric-Ports/Create-Crystal-Clear/issues/6) 我其实一直在关注机械动力的更新（（

作者弃坑 准备更新

**Comment by Qian-F** [comment]
目前待更新附属：

- [Create Crafts & Additions](https://discord.com/channels/806646525605183489/806648956410527824)：已完成，预计周一发布
- [Create: Extended Flywheels](https://github.com/Rabbitminers/Extended-Flywheels/issues/35)：已完成，发布时间未知
- [Create: Steam 'n Rails](https://discord.com/channels/706277846389227612/1044838728243351572)：已完成，将发布1.4版本，发布时间未知

**Comment by Qian-F** [comment]
Create Crafts & Additions ：https://github.com/mrh0/createaddition/pull/593

**Comment by Qian-F** [comment]
计划删除更多飞轮（仅仅是个装饰？

**Comment by Qian-F** [comment]
目前待更新附属：

- [Create Crafts & Additions](https://github.com/mrh0/createaddition/pull/593)：已完成，近期发布
- [Create: Steam 'n Rails](https://discord.com/channels/706277846389227612/1044838728243351572)：已完成，将随forge发布1.4版本，近期发布
- [Create Big Cannons](https://github.com/Cannoneers-of-Create/CreateBigCannons/issues/221)：未完成，等待更新

**Comment by Qian-F** [comment]
Create Crafts & Additions 已更新

- [Create: Steam 'n Rails](https://discord.com/channels/706277846389227612/1044838728243351572/1124414441585393776)：已完成，将随forge发布1.4版本，近期发布
- [Create Big Cannons](https://github.com/Cannoneers-of-Create/CreateBigCannons/issues/221)：未完成，等待更新

**Comment by Qian-F** [comment]
> 计划删除更多飞轮（仅仅是个装饰？

更新了qwq 那就加上

**Comment by Qian-F** [comment]
Create: Steam 'n Rails：已更新
