### ISSUE TITLE
关于小而多的经验球难以吸收且易造成卡顿的问题

### ISSUE THREAD

**Issue by Tonoseihon** [QF-project/QFserver-Wonder#22]
### 检查项

- [X] **我确认增加的内容不会在地图上生成新的结构** 由于服务器地图已经预生成完毕，因此不会同意会增加新建筑/矿物/植物的提案
- [X] **我确认增加的内容不会影响游戏平衡** 例如等价交换、加速火把等Mod不符合服务器宗旨，因此不会添加
- [X] 我已在 [Issues 页面](https://github.com/Qian-F/QFserver-Wonder/issues) 中搜索，确认了这一提案未被提交过。

### 内容

蠹虫经验装置是机械动力中极为便捷的经验获取来源
然而，由于mc原版经验机制的问题（大嘘）
玩家在一定时间内吸收的经验球数量是固定的，无论这个经验球含有多少经验
这导致了蠹虫死亡所产生的经验根本无法在一定时间内吸收完
进而导致堆积的经验球越来越多，进而游戏掉帧，随即服务器卡顿，最后炸服
故希望服务器能加入类似合并经验球数量使经验球减少的模组，如下模组：
https://[www.curseforge.com](https://www.curseforge.com/minecraft/mc-mods/fat-experience-orbs)/minecraft/mc-mods/fat-experience-orbs

**Comment by Qian-F** [comment]
采纳

**Comment by Qian-F** [comment]
已加入服务器
