### ISSUE TITLE
切石机在合成过程中会意外使物品消失

### ISSUE THREAD

**Issue by Tonoseihon** [QF-project/QFserver-Wonder#23]
### 检查项

- [X] **此Bug出现在服务器中** 在单人游戏内的错误/崩溃将不予处理
- [X] **Bug的确是非游戏预期内容** 请在[MC百科](https://mcmod.cn/)/[Curseforge](https://www.curseforge.com/minecraft)/[Modrinth](https://modrinth.com/)中确认这个模组的功能
- [X] 我已在 [ISSUE页面](https://github.com/QF-project/QFserver-Wonder/issues) 中搜索, 确认了这一Bug未被提交过
- [X] **这个Bug是可复现的** 即其他玩家也可以同样触发这个Bug (可选)

### 描述

在使用切石机合成时，倘若我们点击要合成的物品配方后将放入的材料拿出（不是产物）
这时放入的材料会直接消失

### 重现步骤

如下：

https://github.com/QF-project/QFserver-Wonder/assets/99337738/e7cb4d0a-5dad-496f-957d-94eb64c4c145

**Comment by Qian-F** [comment]
尝试删除yuushya模组后查看能否复现

**Comment by Qian-F** [comment]
> 尝试删除yuushya模组后查看能否复现

无效

**Comment by Qian-F** [comment]
找不出原因，请求帮助

**Comment by Qian-F** [comment]
附上报错：
https://mclo.gs/F08L7yC

**Comment by Qian-F** [comment]
ImmutableCollections的问题在https://github.com/QF-project/QFserver-Wonder/issues/20中也出现了，怀疑是匠魂引起的问题

**Comment by Qian-F** [comment]
> ImmutableCollections的问题在 #20 中也出现了，怀疑是匠魂引起的问题

不是匠魂的问题 其他mod导致

**Comment by Qian-F** [comment]
目前的情况是貌似和动过切石机的mod没有关系？这就有很大的问题了。。。
过几天用二分法测试吧，反正机械动力的更新也早。。。

**Comment by Qian-F** [comment]
与item banning冲突 此模组功能可以使用kjs实现 下版本删除
