### ISSUE TITLE
建议删除Create Enchant Additions模组

### ISSUE THREAD

**Issue by Tonoseihon** [QF-project/QFserver-Wonder#24]
### 检查项

- [X] **我确认增加的内容不会在地图上生成新的结构** 由于服务器地图已经预生成完毕，因此不会同意会增加新建筑/矿物/植物的提案
- [x] **我确认增加的内容不会影响游戏平衡** 例如等价交换、加速火把等Mod不符合服务器宗旨，因此不会添加
- [X] 我已在 [Issues 页面](https://github.com/Qian-F/QFserver-Wonder/issues) 中搜索，确认了这一提案未被提交过。

### 内容

Create Enchant Additions模组提供了杀凋石和玻璃等一系列在凋零加强前可以使用的物品
然而在加装了凋零加强的当前游戏中，连基岩都能被打破的环境，该类型方块毫无作用
除此之外还提供了附魔提取器这一鸡肋物品
作为全项提取，charm的砂轮提取的便携程度远超于它
作为单项提取，紫晶工艺中的祛魔台更是远胜于它

综上，该模组在当前游戏中的意义接近为零，故建议删除该模组

**Comment by Qian-F** [comment]
采纳
