### ISSUE TITLE
铜管模组导致潜影盒内可以嵌套潜影盒

### ISSUE THREAD

**Issue by Tonoseihon** [QF-project/QFserver-Wonder#3]
### 检查项

- [X] **这个Bug是可复现的** 即其他玩家也可以同样触发这个Bug (可选)
- [X] **Bug的确是非游戏预期内容** 请在[MC模组百科](https://mcmod.cn/)中确认这个模组的功能
- [X] 我已在 [Issues 页面](https://github.com/Qian-F/QFserver-Wonder/issues) 中搜索，确认了这一Bug未被提交过。

### 描述

通过向潜影盒接入铜管，可以通过铜管的运输将本不可能放入潜影盒的物品放入潜影盒
<img width="425" alt="image" src="https://github.com/Qian-F/QFserver-Wonder/assets/99337738/c3c7e5c7-a6b0-42ea-9241-15ded044a7b1">
注：已删除更多潜影盒mod

### 重现步骤

如下：

https://github.com/Qian-F/QFserver-Wonder/assets/99337738/f9919126-61f1-4916-bfcb-3a39385001c9

**Comment by Qian-F** [comment]
尝试仅安装这两个模组能否复现此问题

**Comment by Tonoseihon** [comment]
会

**Comment by Qian-F** [comment]
> 会

铜管模组在cf和mo上的版本号很混乱，在使用的版本为1.12但是最新版本为1.12a，可能作者最近修改了上传的文件，不得而知，我在复测

**Comment by Qian-F** [comment]
> > 会
> 
> 铜管模组在cf和mo上的版本号很混乱，在使用的版本为1.12但是最新版本为1.12a，可能作者最近修改了上传的文件，不得而知，我在复测

已验证 确为bug 此为模组bug 稍后提交至模组仓库

**Comment by Qian-F** [comment]
ISSUE已交 https://github.com/AViewFromTheTop/SimpleCopperPipesMC/issues/16

**Comment by Qian-F** [comment]
此模组疑似停更，该问题还有可能成为遗留问题，请求玩家社区帮助

**Comment by Qian-F** [comment]
作者回复了！有希望可以通过作者修复这个bug

**Comment by Qian-F** [comment]
作者已在1.20修复 等待backport

**Comment by Qian-F** [comment]
已解决
